/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bedroom.glb --transform 
Files: bedroom.glb [23.81MB] > /Users/bolajislaptop/Downloads/GitHub For UofA/Celestaris/bedroom-transformed.glb [4.9MB] (79%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bedroom-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Walls.geometry} material={materials.PaletteMaterial001} position={[-0.631, 2.109, -0.86]} />
      <mesh geometry={nodes.chandelier_bulb.geometry} material={nodes.chandelier_bulb.material} position={[0.012, 2.989, -0.049]} scale={0.052} />
      <mesh geometry={nodes.curtain_1.geometry} material={materials.curtain} position={[0.998, 2.82, -1.585]} rotation={[Math.PI / 2, 0, 0]} scale={[1.132, 1, 0.826]} />
      <mesh geometry={nodes.pillows.geometry} material={materials.cushion} position={[-0.3, 1.136, 1.613]} rotation={[3.065, 0, 0]} scale={[0.274, 0.008, 0.244]} />
      <mesh geometry={nodes.bedsheet.geometry} material={materials.bedsheet} position={[-0.643, 0.899, 0.72]} rotation={[-0.702, 0, 0]} scale={[1.091, 1, 0.989]} />
    </group>
  )
}

useGLTF.preload('/bedroom-transformed.glb')
