/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room2.glb --transform 
Files: room2.glb [43.78MB] > /Users/bolajislaptop/Downloads/GitHub For UofA/Celestaris/room2-transformed.glb [2.35MB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Walls.geometry} material={materials.PaletteMaterial001} position={[-0.631, 2.109, -0.86]} />
      <mesh geometry={nodes.phone.geometry} material={materials.PaletteMaterial002} position={[0.394, 1.314, -1.284]} rotation={[0, 0.466, 0]} scale={[0.059, 0.008, 0.111]} />
      <mesh geometry={nodes.Computer.geometry} material={materials.PaletteMaterial003} position={[1.095, 1.588, -1.209]} scale={1.315} />
      <mesh geometry={nodes.Curve006.geometry} material={materials.PaletteMaterial004} position={[1.028, 1.794, -1.207]} rotation={[Math.PI / 2, 0, 0]} scale={1.354} />
      <mesh geometry={nodes.modem.geometry} material={materials.PaletteMaterial005} position={[1.64, 1.818, -1.508]} rotation={[0, 1.522, 0]} />
    </group>
  )
}

useGLTF.preload('/room2-transformed.glb')
