/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.gltf --transform --keepmaterials --keepmeshes --keepnames --shadows 
Files: room.gltf [81.81KB] > /Users/bolajislaptop/Downloads/GitHub For UofA/Celestaris/room-transformed.glb [2.26MB] (-2657%)
*/

import React from 'react'
import { useGLTF, Html } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Walls" castShadow receiveShadow geometry={nodes.Walls.geometry} material={materials.walls} position={[-0.631, 2.109, -0.86]} />
      <mesh name="Floor" castShadow receiveShadow geometry={nodes.Floor.geometry} material={materials.walls} position={[0, 0.15, 0]} />
      <mesh name="Walls001" castShadow receiveShadow geometry={nodes.Walls001.geometry} material={materials.Material} position={[0.442, 3.136, -0.258]} scale={1.938} />
      <group name="Cupboard" position={[-0.787, 1.222, -1.265]} scale={0.836}>
        <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials.walls} />
        <mesh name="Cube001_1" castShadow receiveShadow geometry={nodes.Cube001_1.geometry} material={materials.walls} />
      </group>
      <mesh name="cupboard_handles" castShadow receiveShadow geometry={nodes.cupboard_handles.geometry} material={materials.Cupboard_handles} position={[-0.747, 1.202, -1.031]} scale={[0.02, 0.108, 0.014]} />
      <group name="shelf" position={[1.012, 1.375, -1.388]} rotation={[Math.PI / 2, 0, 0]} scale={1.083}>
        <mesh name="Cube006" castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials.walls} />
        <mesh name="Cube006_1" castShadow receiveShadow geometry={nodes.Cube006_1.geometry} material={materials.Mouse} />
      </group>
      <mesh name="shelf_handles" castShadow receiveShadow geometry={nodes.shelf_handles.geometry} material={materials.Cupboard_handles} position={[1.007, 1.222, -1.229]} scale={[0.022, 0.108, 0.014]} />
      <group name="phone" position={[0.394, 1.314, -1.284]} rotation={[0, 0.466, 0]} scale={[0.059, 0.008, 0.111]}>
        <mesh name="Cube016" castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.bed} />
        <mesh name="Cube016_1" castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.Computer_screen} />
      </group>
      <mesh name="Coffee_cup" castShadow receiveShadow geometry={nodes.Coffee_cup.geometry} material={materials.bed} position={[1.555, 1.298, -1.212]} scale={[0.044, 0.076, 0.044]} />
      <mesh name="computer_stand" castShadow receiveShadow geometry={nodes.computer_stand.geometry} material={materials.Mouse} position={[1.007, 1.311, -1.228]} scale={[-0.117, -0.008, -0.117]} />
      <group name="Computer" position={[1.095, 1.588, -1.209]} scale={1.315}>
      <Html position={[-0.06, 0.05, 0.00585]}  transform occlude scale={1/25}>
      <iframe 
        src="index.html"
        style={{
          border: 'none',
          display: 'block',
          transform: `scale(${window.devicePixelRatio})`, 
          imageRendering: 'crisp-edges'
          //transformOrigin: 'top left',
        }}
        onPointerDown={(e) => e.stopPropagation()} // Prevent pointer events from propagating
          >
              <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui" />
      </iframe>
    </Html>
        <mesh name="Cube010" castShadow receiveShadow geometry={nodes.Cube010.geometry} material={materials.Mouse} />
        <mesh name="Cube010_1" castShadow receiveShadow geometry={nodes.Cube010_1.geometry} material={materials.Computer_screen} />
        <mesh name="Cube010_2" castShadow receiveShadow geometry={nodes.Cube010_2.geometry} material={materials.computer_light} />
      </group>
      <mesh name="keyboard" castShadow receiveShadow geometry={nodes.keyboard.geometry} material={materials.Mouse} position={[1.018, 1.302, -0.936]} />
      <group name="mouse" position={[1.478, 1.314, -0.972]} scale={[-0.035, -0.025, -0.08]}>
        <mesh name="Cube019" castShadow receiveShadow geometry={nodes.Cube019.geometry} material={materials.Mouse} />
        <mesh name="Cube019_1" castShadow receiveShadow geometry={nodes.Cube019_1.geometry} material={materials.mouse_scroller} />
      </group>
      <mesh name="Curve006" castShadow receiveShadow geometry={nodes.Curve006.geometry} material={materials.Netflix} position={[1.028, 1.794, -1.207]} rotation={[Math.PI / 2, 0, 0]} scale={1.354} />
      <mesh name="Curve" castShadow receiveShadow geometry={nodes.Curve.geometry} material={materials.Netflix} position={[1.011, 1.557, -1.207]} rotation={[Math.PI / 2, 0, 0]} scale={1.895} />
      <group name="modem" position={[1.64, 1.818, -1.508]} rotation={[0, 1.522, 0]}>
        <mesh name="Cube011" castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials.modem} />
        <mesh name="Cube011_1" castShadow receiveShadow geometry={nodes.Cube011_1.geometry} material={materials.modem_light} />
      </group>
      <mesh name="modem_text" castShadow receiveShadow geometry={nodes.modem_text.geometry} material={materials.Mouse} position={[1.633, 1.916, -1.5]} rotation={[1.122, -0.021, 0.044]} scale={0.014} />
      <group name="speakers" position={[-1.312, 3.386, -1.429]} scale={0.853}>
        <mesh name="Cube003" castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials.Mouse} />
        <mesh name="Cube003_1" castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials.computer_light} />
        <mesh name="Cube003_2" castShadow receiveShadow geometry={nodes.Cube003_2.geometry} material={materials.mouse_scroller} />
      </group>
      <group name="speakers001" position={[-0.358, 3.386, -1.429]} scale={0.853}>
        <mesh name="Cube003" castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials.Mouse} />
        <mesh name="Cube003_1" castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials.computer_light} />
        <mesh name="Cube003_2" castShadow receiveShadow geometry={nodes.Cube003_2.geometry} material={materials.mouse_scroller} />
      </group>
      <mesh name="Wire" castShadow receiveShadow geometry={nodes.Wire.geometry} material={materials.Mouse} position={[-0.726, 2.802, -1.694]} scale={[-0.009, -0.019, -0.009]} />
      <mesh name="chandelier_stand" castShadow receiveShadow geometry={nodes.chandelier_stand.geometry} material={materials.walls} position={[0, 3.949, 0]} scale={[0.518, 0.211, 0.13]} />
      <mesh name="chandeliers" castShadow receiveShadow geometry={nodes.chandeliers.geometry} material={materials.window_frame} position={[-0.002, 3.296, -0.054]} scale={[0.133, 0.175, 0.133]} />
      <mesh name="chandelier_rod" castShadow receiveShadow geometry={nodes.chandelier_rod.geometry} material={materials.Mouse} position={[0.012, 3.687, -0.054]} scale={[-0.007, -0.085, -0.007]} />
      <mesh name="chandelier_bulb" castShadow receiveShadow geometry={nodes.chandelier_bulb.geometry} material={materials.chandelier_bulb} position={[0.012, 2.989, -0.049]} scale={0.052} />
      <mesh name="curtain_1" castShadow receiveShadow geometry={nodes.curtain_1.geometry} material={materials.modem} position={[0.998, 2.82, -1.585]} rotation={[Math.PI / 2, 0, 0]} scale={[1.132, 1, 0.826]} />
      <mesh name="curtain_1001" castShadow receiveShadow geometry={nodes.curtain_1001.geometry} material={materials.modem} position={[-1.61, 2.183, 0.005]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.765, 1, 1.402]} />
      <mesh name="curtain_railing_1" castShadow receiveShadow geometry={nodes.curtain_railing_1.geometry} material={materials.curtain_railings} position={[0.994, 3.772, -1.63]} scale={[1.118, 1, 1]} />
      <mesh name="curtain_loops_1" castShadow receiveShadow geometry={nodes.curtain_loops_1.geometry} material={materials.curtain_railings} position={[1.555, 3.756, -1.584]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.01, 0.01]} />
      <mesh name="curtain_railing_1001" castShadow receiveShadow geometry={nodes.curtain_railing_1001.geometry} material={materials.curtain_railings} position={[-1.657, 3.772, 0.729]} rotation={[0, Math.PI / 2, 0]} scale={[1.118, 1, 1]} />
      <mesh name="curtain_loops_1001" castShadow receiveShadow geometry={nodes.curtain_loops_1001.geometry} material={materials.curtain_railings} position={[-1.612, 3.756, -0.376]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.011, 0.01, 0.01]} />
      <mesh name="lamp" castShadow receiveShadow geometry={nodes.lamp.geometry} material={materials.lamp} position={[-1.531, 3.39, -0.752]} scale={[0.163, 0.253, 0.163]} />
      <mesh name="lamp_handle" castShadow receiveShadow geometry={nodes.lamp_handle.geometry} material={materials.lamp_handle} position={[-1.66, 3.135, -0.75]} scale={[0.025, 0.153, 0.051]} />
      <mesh name="bed" castShadow receiveShadow geometry={nodes.bed.geometry} material={materials.bed} position={[-0.691, 0.956, 1.398]} />
      <mesh name="pillows" castShadow receiveShadow geometry={nodes.pillows.geometry} material={materials.cushion} position={[-0.3, 1.136, 1.613]} rotation={[3.065, 0, 0]} scale={[0.274, 0.008, 0.244]} />
      <mesh name="bed_stands" castShadow receiveShadow geometry={nodes.bed_stands.geometry} material={materials.Mouse} position={[-0.686, 0.358, 0.736]} scale={[-0.03, -0.058, -0.03]} />
      <mesh name="bedsheet" castShadow receiveShadow geometry={nodes.bedsheet.geometry} material={materials.modem} position={[-0.643, 0.899, 0.72]} rotation={[-0.702, 0, 0]} scale={[1.091, 1, 0.989]} />
      <mesh name="matress" castShadow receiveShadow geometry={nodes.matress.geometry} material={materials.modem} position={[-0.687, 0.844, 0.699]} scale={[0.657, 0.101, 1.008]} />
      <mesh name="pillows001" castShadow receiveShadow geometry={nodes.pillows001.geometry} material={materials.cushion} position={[-0.479, 1.091, 0.671]} rotation={[3.065, 0, 0]} scale={[0.274, 0.008, 0.244]} />
      <mesh name="pillows002" castShadow receiveShadow geometry={nodes.pillows002.geometry} material={materials.cushion} position={[-0.942, 1.066, 1.504]} rotation={[3.065, 0, 0]} scale={[0.274, 0.006, 0.244]} />
      <group name="book1" position={[0.448, 1.706, -1.497]} scale={[1.108, 1.325, 1.108]}>
        <mesh name="Cube013" castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.book} />
        <mesh name="Cube013_1" castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials.modem} />
      </group>
      <group name="book2" position={[0.448, 1.74, -1.496]} rotation={[0, -0.413, 0]} scale={[1.108, 1.325, 1.108]}>
        <mesh name="Cube013" castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.book} />
        <mesh name="Cube013_1" castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials.modem} />
      </group>
      <group name="book3" position={[0.448, 1.774, -1.497]} rotation={[0, 0.159, 0]} scale={[1.108, 1.325, 1.108]}>
        <mesh name="Cube013" castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.book} />
        <mesh name="Cube013_1" castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials.modem} />
      </group>
      <mesh name="book3_text" castShadow receiveShadow geometry={nodes.book3_text.geometry} material={materials.book_text} position={[0.448, 1.791, -1.492]} rotation={[0, 0.159, 0]} scale={0.047} />
      <group name="window" position={[0.987, 2.828, -1.706]} scale={[1, 0.887, 1]}>
        <mesh name="Cube005" castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials.window_frame} />
        <mesh name="Cube005_1" castShadow receiveShadow geometry={nodes.Cube005_1.geometry} material={materials.Window_emission} />
      </group>
      <group name="window001" position={[-1.881, 2.159, 0.735]}>
        <mesh name="Cube023" castShadow receiveShadow geometry={nodes.Cube023.geometry} material={materials.window_frame} />
        <mesh name="Cube023_1" castShadow receiveShadow geometry={nodes.Cube023_1.geometry} material={materials.Window_emission} />
      </group>
      <mesh name="puffy_chair" castShadow receiveShadow geometry={nodes.puffy_chair.geometry} material={materials.puffy_chair} position={[1.002, 0.502, -0.594]} rotation={[-3.066, 0, -Math.PI]} scale={0.408} />
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')
